### PR TITLE
feat: improve design

### PR DESCRIPTION
**Pull request by jdev082**
This PR improves the design of the popup. It uses a dark-ish shade of orange to look more sleek. It uses a gray shade instead of black. And it uses either sans-serif or a Noto font depending on which is available.
image

### CODE REVIEW

**Comment by jdev082** [comment]
An issue I'm yet to fix, is the fact on sites with light-mode enabled. The popup font looks, distorted.

**Comment by jdev082** [comment]
@Chiroyce1 I fixed the conflicts!

**Review by lankybox02 — COMMENTED** [review]
why the description change??

**Comment by jdev082** [comment]
> why the description change??

It seemed more descriptive and formal.

**Comment by lankybox02** [comment]
> > why the description change??
> 
> It seemed more descriptive and formal.

In any case, it's a lot less formal.

**Comment by Chiroyce1** [comment]
Sorry, not merging any PRs right now.

**Pull request closed without merging**
